# Generated by Django 3.1.7 on 2021-04-01 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forms',
            new_name='Form',
        ),
    ]
