# Generated by Django 3.1.7 on 2021-04-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0002_auto_20210401_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='references',
            field=models.TextField(blank=True),
        ),
    ]
