# Generated by Django 3.1.7 on 2021-04-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0003_auto_20210407_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='num_int',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
