# Generated by Django 3.1.7 on 2021-04-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0003_auto_20210409_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='mudatec_app.address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='rfc',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='company',
            name='social_name',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
