# Generated by Django 3.1.7 on 2021-04-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0004_auto_20210407_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mudatec_app.address'),
        ),
    ]
