# Generated by Django 3.1.7 on 2021-04-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0004_auto_20210414_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='social_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
