# Generated by Django 3.1.7 on 2021-04-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0005_auto_20210414_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='available_dates',
        ),
    ]
