# Generated by Django 3.1.7 on 2021-04-07 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0005_auto_20210407_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='mudatec_app.address'),
        ),
    ]
