# Generated by Django 3.1.7 on 2021-04-09 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0006_auto_20210407_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='customuser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
