# Generated by Django 3.1.7 on 2021-04-17 01:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0007_auto_20210417_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_edited',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(max_length=20), size=None), size=None),
        ),
    ]
