# Generated by Django 3.1.7 on 2021-04-18 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0008_auto_20210417_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ending_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ending_posts', to='mudatec_app.address'),
        ),
        migrations.AlterField(
            model_name='post',
            name='initial_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initial_posts', to='mudatec_app.address'),
        ),
    ]
