# Generated by Django 3.1.7 on 2021-04-09 01:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0008_auto_20210409_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, max_length=20, null=True), size=None), size=None),
        ),
    ]
