# Generated by Django 3.1.7 on 2021-04-20 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0009_auto_20210418_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='mudatec_app.company'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='mudatec_app.post'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to='mudatec_app.company'),
        ),
        migrations.AlterField(
            model_name='form',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='mudatec_app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='customuser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='ending_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ending_posts', to='mudatec_app.address'),
        ),
        migrations.AlterField(
            model_name='post',
            name='initial_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_posts', to='mudatec_app.address'),
        ),
    ]
