# Generated by Django 3.1.7 on 2021-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0010_auto_20210420_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='elevator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='rope_flow',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='stairs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
