# Generated by Django 3.1.7 on 2021-04-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0010_auto_20210409_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
