# Generated by Django 3.1.7 on 2021-04-09 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0011_auto_20210409_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='customuser',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='mudatec_app.customuser'),
            preserve_default=False,
        ),
    ]
