# Generated by Django 3.1.7 on 2021-04-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0012_auto_20210409_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='mudatec_app.post'),
        ),
    ]
