# Generated by Django 3.1.7 on 2021-04-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0016_auto_20210427_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_de_la_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
