# Generated by Django 3.1.7 on 2021-04-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mudatec_app', '0017_auto_20210427_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paypal_order',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
